---
# tasks file for jdk

- name: Download JDK
  shell: ' wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/{{ JAVA_VERSION }}-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-{{ JAVA_VERSION }}-linux-x64.tar.gz -O /tmp/jdk-{{ JAVA_VERSION }}-linux-x64.tar.gz'

- name: Unarchive JDK
  shell: 'tar -zxvf /tmp/jdk-{{ JAVA_VERSION }}-linux-x64.tar.gz -C /tmp'
